# Generated by Django 4.1.7 on 2023-05-12 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='api_app_category',
        ),
    ]
